apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-sprinboot-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/developerpriya/employee-rest-api-k8s.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: springboot

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
